import AboutSection from "@/components/home/AboutSection";
import BankingAPIIntegration from "@/components/home/BankingAPIIntegration ";
import BlogSection from "@/components/home/BlogSection";
import HeroSection from "@/components/home/HeroSection";
import PartenersSection from "@/components/home/PartenersSection";
import ServicesSection from "@/components/home/ServicesSection";
import TestimonialSection from "@/components/home/TestimonialSection";
import TrustSecuritySection from "@/components/home/TrustSecuritySection";
import WhyUsSection from "@/components/home/WhyUsSection";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <HeroSection />
      <AboutSection />
      <BankingAPIIntegration />
      <WhyUsSection />
      <TrustSecuritySection />
      <ServicesSection />
      <BlogSection />
      <PartenersSection />
      <TestimonialSection />
    </>
  );
}
